version: '3.8'

services:
  # MySQL Database
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: attendee_fastapi_db
      MYSQL_USER: admin
      MYSQL_PASSWORD: 11minhan
      MYSQL_ROOT_PASSWORD: 11minhan
    volumes:
      - mysql:/var/lib/mysql
    networks:
      - attendee_network
    ports:
      - "3306:3306"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "admin", "-p11minhan"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Redis for Celery and Caching
  redis:
    image: redis:7-alpine
    networks:
      - attendee_network
    ports:
      - "6379:6379"
    restart: unless-stopped
    volumes:
      - redis:/data/redis
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Adminer for Database Management
  adminer:
    image: adminer:latest
    networks:
      - attendee_network
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      - ADMINER_DEFAULT_SERVER=mysql
      - ADMINER_DESIGN=pepa-linha
      - ADMINER_DEFAULT_DB=attendee_fastapi_db
      - ADMINER_DEFAULT_USERNAME=admin
      - ADMINER_DEFAULT_PASSWORD=11minhan
      - ADMINER_DEFAULT_DRIVER=server
    restart: unless-stopped

  # Build base image chỉ một lần
  attendee-base:
    build:
      context: .
      dockerfile: Dockerfile
    image: attendee-fastapi:latest
    command: ["echo", "Base image built successfully"]

  # FastAPI Main Application
  attendee-app:
    image: attendee-fastapi:latest
    volumes:
      - .:/attendee_fastapi
    networks:
      - attendee_network
    ports:
      - "8000:8000"
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
      attendee-base:
        condition: service_completed_successfully
    environment:
      - DATABASE_URL=mysql+pymysql://admin:11minhan@mysql:3306/attendee_fastapi_db
      - DATABASE_HOST=mysql
      - DATABASE_PORT=3306
      - DATABASE_USER=admin
      - REDIS_URL=redis://redis:6379/5
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - PYTHONPATH=/attendee_fastapi
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
    restart: unless-stopped

  # Celery Worker for Background Tasks
  attendee-worker:
    image: attendee-fastapi:latest
    volumes:
      - .:/attendee_fastapi
    networks:
      - attendee_network
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
      attendee-base:
        condition: service_completed_successfully
    environment:
      - DATABASE_URL=mysql+pymysql://admin:11minhan@mysql:3306/attendee_fastapi_db
      - DATABASE_HOST=mysql
      - DATABASE_PORT=3306
      - DATABASE_USER=admin
      - REDIS_URL=redis://redis:6379/5
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - PYTHONPATH=/attendee_fastapi
      # Bot automation environment
      - DISPLAY=:99
    command: ["celery", "-A", "app.jobs.celery_app", "worker", "-l", "INFO"]
    restart: unless-stopped

  # Celery Beat Scheduler for Scheduled Tasks
  attendee-scheduler:
    image: attendee-fastapi:latest
    volumes:
      - .:/attendee_fastapi
    networks:
      - attendee_network
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
      attendee-base:
        condition: service_completed_successfully
    environment:
      - DATABASE_URL=mysql+pymysql://admin:11minhan@mysql:3306/attendee_fastapi_db
      - DATABASE_HOST=mysql
      - DATABASE_PORT=3306
      - DATABASE_USER=admin
      - REDIS_URL=redis://redis:6379/5
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - PYTHONPATH=/attendee_fastapi
    command: ["celery", "-A", "app.jobs.celery_app", "beat", "-l", "INFO"]
    restart: unless-stopped

  # Flower for Celery Monitoring (Optional) - DISABLED due to compatibility issues
  attendee-flower:
    image: attendee-fastapi:latest
    volumes:
      - .:/attendee_fastapi
    networks:
      - attendee_network
    ports:
      - "5555:5555"
    depends_on:
      - redis
      - attendee-base
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - PYTHONPATH=/attendee_fastapi
    command: ["/bin/bash", "-c", "cd /attendee_fastapi && python -m flower --app=app.jobs.celery_app flower --port=5555"]
    restart: unless-stopped

networks:
  attendee_network:
    driver: bridge

volumes:
  mysql:
  redis:


